site_name: "C-Phasing"
site_url: https://wangyibin.github.io/CPhasing
repo_url: https://github.com/wangyibin/CPhasing
copyright: Copyright © 2022-2025 Tanger-lab
theme:
  name: material
  highlight: monokai
  favicon: logo/logo.png
  logo: logo/logo.png
  font:
    text: Red Hat Text
    code: JetBrains Mono

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: prefix-light
      accent: prefix-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: prefix
      accent: prefix
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    edit: material/pencil
    view: material/eye

  features:
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.code.annotate
    # - content.code.select Sponsor only
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.footer
  
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      toc_depth: 3
      permalink: "#"
  - mdx_truly_sane_lists

extra_css:
  - styles/extra.css

extra:
  homepage: https://wangyibin.github.io
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wangyibin
  version:
    provider: mike

plugins:
  - search 
  # - i18n:
  #   docs_structure: suffix
  #   fallback_to_default: true 
  #   reconfigure_material: true 
  #   reconfigure_search: true
  #   languages:
  #     - locale: en
  #       default: true 
  #       name: English
  #       build: true 
  #       site_name: "C-Phasing documentation (en)"
  #     - locale: zh 
  #       name: 简体中文
  #       build: true  
  #       site_name: "C-Phasing documentation (Zh)"
  

nav:
  - Installation: index.md
  - Basic Usage: basic_usage.md
  - FAQ: faq.md