[project]
authors = ["wangyibin <yibinwang96@outlook.com>"]
channels = ["conda-forge", "bioconda", "anaconda"]
description = "Add a short description here"
name = "CPhasing"
platforms = ["linux-64"]
version = "0.2.0.r269"

[system-requirements]
linux = "3.10.0"
libc = "2.17"


[tasks]
activate = "LD_LIBRARY_PATH=$PWD/.pixi/envs/default/lib:$LD_LIBRARY_PATH"

[dependencies]
python = "3.12.2.*"
rich-click = ">=1.8.3,<2"
biopython = ">=1.84,<2"
click-didyoumean = ">=0.3.1,<0.4"
colormaps = ">=0.4.2,<0.5"
dask = ">=2024.11.2,<2025"
matplotlib = ">=3.9.2,<4"
pyranges = ">=0.1.2,<0.2"
joblib = ">=1.4.2,<2"
pandarallel = ">=1.6.5,<2"
natsort = ">=8.4.0,<9"
ncls = ">=0.0.68,<0.0.69"
cooler = ">=0.10.2,<0.11"
msgspec = ">=0.18.6,<0.19"
pandas = ">=2.2.3,<3"
numpy = ">=1.26.4,<2"
polars = ">=1.16.0,<2"
portion = ">=2.5.0,<3"
patchworklib = ">=0.6.3,<0.7"
python-igraph = ">=0.11.8,<0.12"
networkx = ">=3.4.2,<4"
pyarrow = ">=18.1.0,<19"
intervaltree = ">=3.1.0,<4"
hicmatrix = ">=17.2,<18"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.5.2,<2"
pytools = ">=2024.1.18,<2025"
pysam = ">=0.22.1,<0.23"
ray = ">=2.3.1,<3"
minimap2 = ">=2.28,<3"
chromap = ">=0.2.7,<0.3"
bedtools = ">=2.31.1,<3"
seqkit = ">=2.9.0,<3"
samtools = ">=1.21,<2"
pigz = ">=2.8,<3"
